on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    steps:
      - name: 24ds3000010@ds.study.iitm.ac.in
        run: echo "Hello, world!"



